## Set up

In [1]:
import pandas as pd

## Input Arguments

In [10]:
DATASET_DP = f"../data/yelp_dataset/sample/sample_100_biz"

## Load data

In [11]:
review_df = pd.read_parquet(f"{DATASET_DP}/yelp_academic_dataset_review_sample_100_biz.parquet")

In [13]:
review_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,L0jv8c2FbpWSlfNC6bbUEA,bFPdtzu11Oi0f92EAcjqmg,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,What a great addition to the Funk Zone! Grab ...,2016-10-13 22:50:47
1,mMwnX1vc3tQUeDNS2wiKFw,f10WH1fXhy-68r4AEEhAWA,9OG5YkX1g2GReZM0AskizA,4,0,0,0,Great bar Happy Hour 4-7 every day. Wine & Dra...,2016-01-30 03:16:46
2,uwPhE21CZLlp1kkSMPvvYw,5OnQqP3q2_9auNdDKpLdsw,WKMJwqnfZKsAae75RMP6jA,3,0,0,0,So much to like about this place--the beautifu...,2012-11-06 23:35:15
3,6odPSjoPWOyeDQpgJbdGaA,jLr7vcDg43TqS2OK4ROvPQ,oaboaRBUgGjbo2kfUIKDLQ,5,0,0,0,Super tasty and enormous portions. Some unique...,2016-03-30 23:22:54
4,LFpaQzYkP5Pzm5lEjJpTRw,Ttb21DpWqphQMNSS5TXgMA,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,Possibly the best breakfast sandwich EVER. On...,2017-01-15 00:36:04
...,...,...,...,...,...,...,...,...,...
5235,9cpaQho8MbRujLCw4YC2vg,sRjJja-1_xZHTua5b1s8nA,YNjyv0gfOr2g8lbmUpTnKg,4,0,0,0,Food is always delicious. Best way to try diff...,2021-12-02 03:14:14
5236,Me2ixr2UWaqnMWTGFwkyRQ,Y_CWjc7mz6jaebDxyyVViw,MUTTqe8uqyMdBl186RmNeA,5,0,0,0,Tuna Bar has quickly become a favorite of Phil...,2021-12-04 01:21:49
5237,yP6qECsUSGs4Jsnr2Pu5KQ,BpfStJAeH3-8mnvZKwh1qg,MUTTqe8uqyMdBl186RmNeA,5,1,1,1,5 stars ALL AROUND! The sushi here is amazing....,2017-12-31 13:51:49
5238,s88sTzb8FPtxGvAjqhNuTQ,nHXo42Jq950NrEbCyvF4UA,seKihQKpGGnCeLuELRQPSQ,4,1,2,0,Today was our first visit to Twin Peaks. I did...,2020-09-15 19:44:09
5239,xVxHjZ0ThLqC4Zhv1naU4Q,iJ97UrvPlGNttp44qsJ-4A,oaboaRBUgGjbo2kfUIKDLQ,4,2,0,2,The ice cream du jour downtown was busy but a ...,2022-01-15 03:27:53

## Load business

In [14]:
# load businesses
business_df = pd.read_parquet(f'{DATASET_DP}/yelp_academic_dataset_business_sample_100_biz.parquet')

In [15]:
business_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Shipping Centers, Local Services, Notaries, Ma...","{'Friday': '8:0-18:30', 'Monday': '0:0-0:0', '..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Department Stores, Shopping, Fashion, Home & G...","{'Friday': '8:0-23:0', 'Monday': '8:0-22:0', '..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', '..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Brewpubs, Breweries, Food","{'Friday': '12:0-22:0', 'Monday': None, 'Satur..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,pEm4xNCk8d0TF6A1gi-WDQ,TKO DJs,2650 S Big Bend,Maplewood,MO,63143,38.613576,-90.322383,3.5,17,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Karaoke, DJs, Event Planning & Services, Party...","{'Friday': '9:0-17:0', 'Monday': '9:0-17:0', '..."
96,J_ksUDPpzPwfTGtI4zTRnQ,Riverview Room,600 Decatur St,New Orleans,LA,70130,29.955925,-90.062962,4.5,7,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Event Planning & Services, Caterers, Party & E...","{'Friday': '9:0-16:0', 'Monday': '9:0-16:0', '..."
97,knQ4vIgx-r85kjlWVVjcpQ,Silver and Blue Outfitters,5191 Meadowood Mall Cir,Reno,NV,89502,39.476518,-119.784037,4.5,5,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Sporting Goods, Sports Wear, Fashion, Restaura...","{'Friday': '10:0-21:0', 'Monday': '0:0-0:0', '..."
98,U2Tzy6J9aAAg9pzXsgdkvg,Premier Mortgage Resources,"3363 E Presidential Dr, Ste 200",Meridian,ID,83642,43.614194,-116.352500,5.0,6,1,None,"Real Estate, Home Services, Financial Services...","{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa..."
99,1MeIwdbTnZOBFCKOrgaxuw,Ricardo's Italian Cafe,1931 Park Ave,Saint Louis,MO,63104,38.617272,-90.212784,3.5,80,0,"{'AcceptsInsurance': None, 'Alcohol': 'u'full_...","American (New), Restaurants, Cafes, Italian, A...","{'Friday': '16:0-22:0', 'Monday': '11:0-14:0',..."

## Join Business & Review

In [18]:
denom_df = (
    pd.merge(
        # TODO: fix duplicated columns
        review_df.rename(columns={'stars': 'review_stars'}),
        business_df.add_prefix("biz_").rename(columns={"biz_business_id": "business_id"}),
        how="left",
        on="business_id",
        validate="m:1"
    )
)
denom_df

,review_id,user_id,business_id,review_stars,useful,funny,cool,text,date,biz_name,...,biz_state,biz_postal_code,biz_latitude,biz_longitude,biz_stars,biz_review_count,biz_is_open,biz_attributes,biz_categories,biz_hours
0,L0jv8c2FbpWSlfNC6bbUEA,bFPdtzu11Oi0f92EAcjqmg,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,What a great addition to the Funk Zone! Grab ...,2016-10-13 22:50:47,Helena Avenue Bakery,...,CA,93101,34.414445,-119.690672,4.0,389,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Food, Restaurants, Salad, Coffee & Tea, Breakf...","{'Friday': '8:0-14:0', 'Monday': '0:0-0:0', 'S..."
1,mMwnX1vc3tQUeDNS2wiKFw,f10WH1fXhy-68r4AEEhAWA,9OG5YkX1g2GReZM0AskizA,4,0,0,0,Great bar Happy Hour 4-7 every day. Wine & Dra...,2016-01-30 03:16:46,Romano's Macaroni Grill,...,NV,89502,39.476117,-119.789339,2.5,339,1,"{'AcceptsInsurance': None, 'Alcohol': ''full_b...","Restaurants, Italian","{'Friday': '11:0-21:0', 'Monday': '11:0-22:0',..."
2,uwPhE21CZLlp1kkSMPvvYw,5OnQqP3q2_9auNdDKpLdsw,WKMJwqnfZKsAae75RMP6jA,3,0,0,0,So much to like about this place--the beautifu...,2012-11-06 23:35:15,Roast Coffeehouse and Wine Bar,...,AB,T5J 1B9,53.546045,-113.499169,4.0,40,0,"{'AcceptsInsurance': None, 'Alcohol': 'u'beer_...","Coffee & Tea, Food, Cafes, Bars, Wine Bars, Re...","{'Friday': '8:0-18:0', 'Monday': '8:0-18:0', '..."
3,6odPSjoPWOyeDQpgJbdGaA,jLr7vcDg43TqS2OK4ROvPQ,oaboaRBUgGjbo2kfUIKDLQ,5,0,0,0,Super tasty and enormous portions. Some unique...,2016-03-30 23:22:54,Mike's Ice Cream,...,TN,37201,36.162649,-86.775973,4.5,593,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Ice Cream & Frozen Yogurt, Coffee & Tea, Resta...","{'Friday': '8:0-0:0', 'Monday': '8:0-23:0', 'S..."
4,LFpaQzYkP5Pzm5lEjJpTRw,Ttb21DpWqphQMNSS5TXgMA,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,Possibly the best breakfast sandwich EVER. On...,2017-01-15 00:36:04,Helena Avenue Bakery,...,CA,93101,34.414445,-119.690672,4.0,389,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Food, Restaurants, Salad, Coffee & Tea, Breakf...","{'Friday': '8:0-14:0', 'Monday': '0:0-0:0', 'S..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5235,9cpaQho8MbRujLCw4YC2vg,sRjJja-1_xZHTua5b1s8nA,YNjyv0gfOr2g8lbmUpTnKg,4,0,0,0,Food is always delicious. Best way to try diff...,2021-12-02 03:14:14,Copper Vine,...,LA,70112,29.950647,-90.074427,4.5,350,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'full_...","Nightlife, Pubs, Event Planning & Services, Wi...","{'Friday': '11:0-23:0', 'Monday': '0:0-0:0', '..."
5236,Me2ixr2UWaqnMWTGFwkyRQ,Y_CWjc7mz6jaebDxyyVViw,MUTTqe8uqyMdBl186RmNeA,5,0,0,0,Tuna Bar has quickly become a favorite of Phil...,2021-12-04 01:21:49,Tuna Bar,...,PA,19106,39.953949,-75.143226,4.0,245,1,"{'AcceptsInsurance': None, 'Alcohol': ''full_b...","Sushi Bars, Restaurants, Japanese","{'Friday': '13:30-23:0', 'Monday': None, 'Satu..."
5237,yP6qECsUSGs4Jsnr2Pu5KQ,BpfStJAeH3-8mnvZKwh1qg,MUTTqe8uqyMdBl186RmNeA,5,1,1,1,5 stars ALL AROUND! The sushi here is amazing....,2017-12-31 13:51:49,Tuna Bar,...,PA,19106,39.953949,-75.143226,4.0,245,1,"{'AcceptsInsurance': None, 'Alcohol': ''full_b...","Sushi Bars, Restaurants, Japanese","{'Friday': '13:30-23:0', 'Monday': None, 'Satu..."
5238,s88sTzb8FPtxGvAjqhNuTQ,nHXo42Jq950NrEbCyvF4UA,seKihQKpGGnCeLuELRQPSQ,4,1,2,0,Today was our first visit to Twin Peaks. I did...,2020-09-15 19:44:09,Twin Peaks,...,IN,46250,39.906295,-86.047463,3.5,257,1,"{'AcceptsInsurance': None, 'Alcohol': ''full_b...","Sports Bars, American (New), American (Traditi...","{'Friday': '11:0-19:0', 'Monday': '0:0-0:0', '..."
5239,xVxHjZ0ThLqC4Zhv1naU4Q,iJ97UrvPlGNttp44qsJ-4A,oaboaRBUgGjbo2kfUIKDLQ,4,2,0,2,The ice cream du jour downtown was busy but a ...,2022-01-15 03:27:53,Mike's Ice Cream,...,TN,37201,36.162649,-86.775973,4.5,593,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Ice Cream & Frozen Yogurt, Coffee & Tea, Resta...","{'Friday': '8:0-0:0', 'Monday': '8:0-23:0', 'S..."

In [19]:
denom_df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
review_id,5240,5240,L0jv8c2FbpWSlfNC6bbUEA,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_id,5240,4984,wXdbkFZsfDR7utJvbWElyA,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
business_id,5240,100,oaboaRBUgGjbo2kfUIKDLQ,601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_stars,5240.0,NaN,NaN,NaN,3.771756,1.0,3.0,4.0,5.0,5.0,1.454339
useful,5240.0,NaN,NaN,NaN,1.060305,0.0,0.0,0.0,1.0,149.0,3.102897
funny,5240.0,NaN,NaN,NaN,0.307252,0.0,0.0,0.0,0.0,133.0,2.152664
cool,5240.0,NaN,NaN,NaN,0.532824,0.0,0.0,0.0,0.0,145.0,2.689376
text,5240,5231,"Homemade Ice Cream, hand crafted Milkshakes, b...",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,5240,NaN,NaN,NaN,2017-06-25 15:35:16.198854912,2005-04-03 05:16:43,2015-07-21 12:35:09,2018-02-05 20:03:03,2019-09-09 00:52:26.500000,2022-01-19 19:45:32,NaN
biz_name,5240,99,Mike's Ice Cream,601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_address,5240,95,129 2nd Ave N,601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_city,5240,53,Nashville,953,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_state,5240,14,PA,1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_postal_code,5240,89,37201,762,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_latitude,5240.0,NaN,NaN,NaN,37.066456,27.76659,34.414445,38.896563,39.939825,53.549633,4.567233
biz_longitude,5240.0,NaN,NaN,NaN,-90.235306,-119.847204,-90.186203,-86.773197,-75.643331,-74.825821,15.29051
biz_stars,5240.0,NaN,NaN,NaN,3.782824,1.5,3.5,4.0,4.5,5.0,0.808944
biz_review_count,5240.0,NaN,NaN,NaN,215.246183,5.0,56.0,159.0,350.0,593.0,183.413246
biz_is_open,5240.0,NaN,NaN,NaN,0.787595,0.0,1.0,1.0,1.0,1.0,0.409049
biz_attributes,5063,84,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...",601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_categories,5240,98,"Ice Cream & Frozen Yogurt, Coffee & Tea, Resta...",601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_hours,4791,77,"{'Friday': '8:0-0:0', 'Monday': '8:0-23:0', 'S...",601,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Persist data

In [20]:
DENOM_REVIEW_FD = f"{DATASET_DP}/denom_review.parquet"
denom_df.to_parquet(DENOM_REVIEW_FD, index=False)